# Importing libraries and Dataset

In [1]:
import pandas as pd
messages = pd.read_csv('SMSSpamCollection.txt', sep='\t',
                           names=["label", "message"])

In [2]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# Data Cleaning and Preprocessing

In [3]:
import nltk
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [4]:
# Importing libraries for stemming
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [5]:
corpus= []
for i in range(0 , len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

# Creating  BOW (Bag of Words)






In [7]:
# Create Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
# for binary Bow enable binary = true
cv = CountVectorizer(max_features=2500 , ngram_range=(1,2))


In [8]:
x = cv.fit_transform(corpus).toarray()

In [9]:
import numpy as np
np.set_printoptions(edgeitems = 30, linewidth = 100000 , formatter= dict(float = lambda x: "%.3g" % x))
# Configures the way NumPy arrays are displayed in your notebook
"""
edgeitems = 30: This setting controls the number of elements displayed at the beginning and end of
each dimension when printing large arrays

linewidth = 100000: This determines the maximum number of characters allowed on a single line when
printing an array.

formatter=dict(float=lambda x: "%.3g" % x): This part customizes the formatting of floating-point
numbers within the array. The lambda function is used to format floats with three significant
digits using the "%.3g" format specifier.
"""
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [10]:
# vocabulary
cv.vocabulary_

{'go': 795,
 'point': 1607,
 'crazi': 456,
 'avail': 114,
 'bugi': 225,
 'great': 852,
 'world': 2429,
 'la': 1103,
 'cine': 352,
 'got': 840,
 'wat': 2337,
 'ok': 1481,
 'lar': 1114,
 'joke': 1071,
 'wif': 2395,
 'free': 709,
 'entri': 612,
 'wkli': 2419,
 'comp': 406,
 'win': 2400,
 'cup': 471,
 'final': 677,
 'st': 1979,
 'may': 1269,
 'text': 2083,
 'receiv': 1704,
 'question': 1665,
 'std': 1992,
 'txt': 2196,
 'rate': 1682,
 'appli': 78,
 'free entri': 714,
 'entri wkli': 614,
 'std txt': 1993,
 'txt rate': 2202,
 'rate appli': 1684,
 'dun': 573,
 'say': 1803,
 'earli': 579,
 'alreadi': 50,
 'nah': 1392,
 'think': 2103,
 'goe': 815,
 'usf': 2270,
 'live': 1178,
 'around': 90,
 'though': 2111,
 'freemsg': 721,
 'hey': 927,
 'darl': 487,
 'week': 2363,
 'word': 2425,
 'back': 131,
 'like': 1164,
 'fun': 743,
 'still': 1995,
 'tb': 2063,
 'xxx': 2465,
 'send': 1838,
 'even': 622,
 'brother': 214,
 'speak': 1963,
 'treat': 2170,
 'per': 1550,
 'request': 1741,
 'mell': 1281,
 'oru': 

# Label Encoding

In [11]:
# Output Features
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values

In [12]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

# Training and Testing the data

In [13]:
# Train Test spilt
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)


In [14]:
# Will be using Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(x_train , y_train)

In [15]:
spam_detect_model

MultinomialNB()

In [17]:
y_pred = spam_detect_model.predict(x_test)

# Checking the Accuracy and Classification Report

In [18]:
# Importing the metrics
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report


In [19]:
accuracy_score(y_test , y_pred)

0.9874439461883409

In [20]:
classification_report(y_test , y_pred)

'              precision    recall  f1-score   support\n\n       False       0.98      0.93      0.96       160\n        True       0.99      1.00      0.99       955\n\n    accuracy                           0.99      1115\n   macro avg       0.98      0.96      0.97      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [21]:
confusion_matrix(y_test , y_pred)

array([[149,  11],
       [  3, 952]])

# Creating TF IDF

In [22]:
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20 , random_state=0)

In [23]:
# Importing and creating TF IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [24]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [25]:
X_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0.145, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [26]:
tv.vocabulary_

{'good': 882,
 'movi': 1400,
 'ok': 1507,
 'leav': 1170,
 'free': 768,
 'give': 844,
 'otherwis': 1546,
 'someth': 1948,
 'mayb': 1310,
 'bit': 177,
 'hope': 1006,
 'got': 897,
 'home': 1002,
 'babe': 131,
 'still': 2000,
 'awak': 122,
 'sinc': 1910,
 'alreadi': 54,
 'workin': 2439,
 'get': 824,
 'job': 1096,
 'said': 1808,
 'matter': 1302,
 'mind': 1344,
 'say': 1823,
 'oh': 1504,
 'yeah': 2482,
 'diet': 556,
 'oh yeah': 1506,
 'sorri': 1958,
 'thing': 2119,
 'may': 1309,
 'pub': 1690,
 'later': 1152,
 'ill': 1045,
 'call': 242,
 'even': 660,
 'idea': 1039,
 'dear': 524,
 'reach': 1721,
 'room': 1791,
 'dear reach': 528,
 'look': 1227,
 'daddi': 498,
 'want': 2346,
 'eat': 617,
 'night': 1466,
 'long': 1224,
 'chennai': 334,
 'sure': 2051,
 'pick': 1597,
 'us': 2295,
 'competit': 408,
 'da': 495,
 'car': 287,
 'park': 1560,
 'da car': 496,
 'okay': 1518,
 'soon': 1955,
 'best': 165,
 'yar': 2476,
 'els': 628,
 'thk': 2127,
 'sort': 1962,
 'funni': 803,
 'yup': 2498,
 'izzit': 1086,
 '

# Using the Naive Bayes Classification

In [27]:
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [29]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

# Metrics for TF IDF

In [30]:
accuracy_score(y_test,y_pred)


0.9775784753363229

In [31]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n       False       1.00      0.84      0.92       160\n        True       0.97      1.00      0.99       955\n\n    accuracy                           0.98      1115\n   macro avg       0.99      0.92      0.95      1115\nweighted avg       0.98      0.98      0.98      1115\n'

In [32]:
confusion_matrix(y_test,y_pred)

array([[135,  25],
       [  0, 955]])